# Generated by Django 5.1.7 on 2025-04-18 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_rename_posted_at_announcement_created_at_and_more'),
    ]

    operations = [
        # Add created_at to Module
        migrations.AddField(
            model_name='Module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        ),
        # Add created_at to Reminder
        migrations.AddField(
            model_name='Reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        ),
        # Update created_by in Announcement to non-nullable
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('core', 'Announcement').objects.filter(created_by__isnull=True).update(created_by=6),  # rohan's ID
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AlterField(
            model_name='Announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=models.CASCADE, to='core.user'),
        ),
    ]
