# Generated by Django 5.1.7 on 2025-04-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20250418_1055'),
    ]

    operations = [
        # Update NULL values in created_by_id to rohan's ID (6)
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('core', 'Announcement').objects.filter(created_by_id__isnull=True).update(created_by_id=6),
            reverse_code=lambda apps, schema_editor: None,
        ),
        # Ensure created_by field is non-nullable
        migrations.AlterField(
            model_name='Announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=models.CASCADE, to='core.user'),
        ),
    ]
