# Generated by Django 5.1.7 on 2025-04-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_result_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
