from django.urls import path
from .views import (
    homepage_view, signup_view, verify_otp_signup, login_view, student_login, teacher_login, admin_login,
    verify_otp, logout_view, admin_dashboard_view, admin_create_program, admin_create_module, admin_assign_teacher,
    admin_enroll_student, admin_add_user, admin_edit_user, admin_delete_user, admin_edit_program, admin_delete_program,
    admin_edit_module, admin_delete_module, teacher_dashboard_view, teacher_manage_resources, teacher_delete_resource,
    teacher_share_assignment, teacher_post_announcement, teacher_publish_result, student_dashboard_view,
    student_choose_program, student_pomodoro_timer, student_set_reminder, student_submit_assignment, teacher_delete_announcement,
    teacher_edit_resource,teacher_edit_announcement,teacher_delete_assignment, teacher_edit_assignment,
    student_create_reminder, student_edit_reminder, student_delete_reminder
)
# student_gpa_prediction, student_course_recommendation
urlpatterns = [
    path('', homepage_view, name='homepage'),
    path('signup/', signup_view, name='signup'),
    path('verify-otp-signup/', verify_otp_signup, name='verify_otp_signup'),
    path('login/', login_view, name='login'),
    path('student-login/', student_login, name='student_login'),
    path('teacher-login/', teacher_login, name='teacher_login'),
    path('admin-login/', admin_login, name='admin_login'),
    path('verify-otp/', verify_otp, name='verify_otp'),
    path('logout/', logout_view, name='logout'),
    path('admin/dashboard/', admin_dashboard_view, name='admin_dashboard'),
    path('admin/add-user/', admin_add_user, name='admin_add_user'),
    path('admin/edit-user/<int:user_id>/', admin_edit_user, name='admin_edit_user'),
    path('admin/delete-user/<int:user_id>/', admin_delete_user, name='admin_delete_user'),
    path('admin/create-program/', admin_create_program, name='admin_create_program'),
    path('admin/edit-program/<int:program_id>/', admin_edit_program, name='admin_edit_program'),
    path('admin/delete-program/<int:program_id>/', admin_delete_program, name='admin_delete_program'),
    path('admin/create-module/', admin_create_module, name='admin_create_module'),
    path('admin/edit-module/<int:module_id>/', admin_edit_module, name='admin_edit_module'),
    path('admin/delete-module/<int:module_id>/', admin_delete_module, name='admin_delete_module'),
    path('admin/assign-teacher/<int:module_id>/', admin_assign_teacher, name='admin_assign_teacher'),
    path('admin/enroll-student/<int:program_id>/', admin_enroll_student, name='admin_enroll_student'),
    path('teacher/dashboard/', teacher_dashboard_view, name='teacher_dashboard'),
    path('teacher/manage-resources/<int:module_id>/', teacher_manage_resources, name='teacher_manage_resources'),
    path('teacher/delete-resource/<int:resource_id>/', teacher_delete_resource, name='teacher_delete_resource'),
    path('teacher/edit-resource/<int:resource_id>/', teacher_edit_resource, name='teacher_edit_resource'),
    path('teacher/share-assignment/<int:module_id>/', teacher_share_assignment, name='teacher_share_assignment'),
    path('teacher/delete-assignment/<int:assignment_id>/', teacher_delete_assignment, name='teacher_delete_assignment'),
    path('teacher/edit-assignment/<int:assignment_id>/', teacher_edit_assignment, name='teacher_edit_assignment'),
    path('teacher/post-announcement/<int:module_id>/', teacher_post_announcement, name='teacher_post_announcement'),
    path('teacher/edit-announcement/<int:announcement_id>/', teacher_edit_announcement, name='teacher_edit_announcement'),
    path('teacher/delete-announcement/<int:announcement_id>/', teacher_delete_announcement, name='teacher_delete_announcement'),
    path('teacher/publish-result/<int:module_id>/', teacher_publish_result, name='teacher_publish_result'),
    path('student/dashboard/', student_dashboard_view, name='student_dashboard'),
    path('student/submit-assignment/<int:assignment_id>/', student_submit_assignment, name='student_submit_assignment'),
    path('student/create-reminder/', student_create_reminder, name='student_create_reminder'),
    path('student/edit-reminder/<int:reminder_id>/', student_edit_reminder, name='student_edit_reminder'),
    path('student/delete-reminder/<int:reminder_id>/', student_delete_reminder, name='student_delete_reminder')
]